# Generated by Django 3.1.3 on 2022-06-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_question_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioncount',
            name='ip',
        ),
    ]
