# Generated by Django 3.1.3 on 2022-06-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0009_remove_questioncount_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='view_count',
        ),
        migrations.AddField(
            model_name='questioncount',
            name='ip',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
